[en]
languageName = "English"
contentDir = "content/en"
weight = 10
[en.params]
languageISO = "EN"
languageTag = "en-US"
footer = 'Brought to you by <a class="text-muted" href="https://sifterstudios.no">Sifterstudios</a>'
get_started = 'HALLO'

[no]
languageName = "Norsk"
contentDir = "content/no"
weight = 5
[no.params]
languageISO = "NO"
languageTag = "no-NO"
footer = 'Laget av <a class="text-muted" href="https://sifterstudios.no">Sifterstudios</a>'
get_started = 'HALLO'
