[[main]]
name = "Info"
url = "/docs/info/"
weight = 10

[[social]]
name = "GitHub"
pre = '<svg fill="#ff5a5f" width="24px" height="24px" viewBox="0 0 24 24" id="airbnb" data-name="Flat Line" xmlns="http://www.w3.org/2000/svg" class="icon flat-line"><path id="primary" d="M14,14h0a4.83,4.83,0,0,1-1.41,3.41L10,20a3.54,3.54,0,0,1-2.5,1h0A3.53,3.53,0,0,1,4,17.46H4A10.47,10.47,0,0,1,5.1,12.8l4-8A3.21,3.21,0,0,1,12,3h0a3.21,3.21,0,0,1,2.89,1.79l4,8A10.47,10.47,0,0,1,20,17.46h0A3.53,3.53,0,0,1,16.46,21h0A3.54,3.54,0,0,1,14,20l-2.55-2.55A4.83,4.83,0,0,1,10,14h0a2,2,0,0,1,2-2h0A2,2,0,0,1,14,14Z" style="fill: none; stroke: rgb(255, 90, 95); stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;"></path></svg>'
url = "https://www.airbnb.no/rooms/1289061827455900501?viralityEntryPoint=1&unique_share_id=0E08AB5F-4AC5-4B90-B0A5-35B3EF54ADEB&slcid=7b81c062ebe64adcb3a25d6ea359f556&s=76&feature=share&adults=1&channel=native&slug=SgC2IZoN"
post = "v0.1.0"
weight = 30

[[sidebar_docs]]
name = "Guides"
pageRef = "/docs/guides"
weight = 10

[[sidebar_docs]]
name = "Reference"
pageRef = "/docs/reference"
weight = 20

[[sidebar_docs]]
name = "Resources"
pageRef = "/docs/resources"
weight = 30

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy/"
# weight = 10

# [[footer]]
#   name = "Terms of Service"
#   url = "/terms/"
#   weight = 20
