[[main]]
name = "Info"
url = "/info/"
weight = 10


# [[social]]
#   name = "X"
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4l11.733 16h4.267l-11.733 -16z"></path><path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772"></path></svg>'
#   url = "https://twitter.com/getdoks"
#   weight = 10
#
# [[social]]
#   name = "Discord"
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-discord" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M8 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M14 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M8.5 17c0 1 -1.356 3 -1.832 3c-1.429 0 -2.698 -1.667 -3.333 -3c-.635 -1.667 -.476 -5.833 1.428 -11.5c1.388 -1.015 2.782 -1.34 4.237 -1.5l.975 1.923a11.913 11.913 0 0 1 4.053 0l.972 -1.923c1.5 .16 3.043 .485 4.5 1.5c2 5.667 2.167 9.833 1.5 11.5c-.667 1.333 -2 3 -3.5 3c-.5 0 -2 -2 -2 -3"></path><path d="M7 16.5c3.5 1 6.5 1 10 0"></path></svg>'
#   url = "https://getdoks.org/chat"
#   weight = 20

[[social]]
name = "GitHub"
pre = '<svg fill="#ff5a5f" width="24px" height="24px" viewBox="0 0 24 24" id="airbnb" data-name="Flat Line" xmlns="http://www.w3.org/2000/svg" class="icon flat-line"><path id="primary" d="M14,14h0a4.83,4.83,0,0,1-1.41,3.41L10,20a3.54,3.54,0,0,1-2.5,1h0A3.53,3.53,0,0,1,4,17.46H4A10.47,10.47,0,0,1,5.1,12.8l4-8A3.21,3.21,0,0,1,12,3h0a3.21,3.21,0,0,1,2.89,1.79l4,8A10.47,10.47,0,0,1,20,17.46h0A3.53,3.53,0,0,1,16.46,21h0A3.54,3.54,0,0,1,14,20l-2.55-2.55A4.83,4.83,0,0,1,10,14h0a2,2,0,0,1,2-2h0A2,2,0,0,1,14,14Z" style="fill: none; stroke: rgb(255, 90, 95); stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;"></path></svg>'
url = "https://www.airbnb.no/rooms/1289061827455900501?viralityEntryPoint=1&unique_share_id=0E08AB5F-4AC5-4B90-B0A5-35B3EF54ADEB&slcid=7b81c062ebe64adcb3a25d6ea359f556&s=76&feature=share&adults=1&channel=native&slug=SgC2IZoN"
post = "v0.1.0"
weight = 30

# [[sidebar_docs]]
#   name = "Guides"
#   pageRef = "/docs/guides"
#   weight = 10
#
# [[sidebar_docs]]
#   name = "Reference"
#   pageRef = "/docs/reference"
#   weight = 20
#
# [[sidebar_docs]]
#   name = "Resources"
#   pageRef = "/docs/resources"
#   weight = 30

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy/"
# weight = 10

# [[footer]]
#   name = "Terms of Service"
#   url = "/terms/"
#   weight = 20
